---
apiVersion: v1
kind: Pod
metadata:
  name: github-runner-debian
  labels:
    app: github-runner
    runner: debian
    environment: production
spec:
  restartPolicy: Always

  containers:
  - name: github-runner-debian
    image: localhost/github-runner-debian:latest
    imagePullPolicy: Never

    # Environment variables
    envFrom:
    - configMapRef:
        name: runner-config
        optional: true

    env:
    - name: RUNNER_NAME
      value: "debian-runner-ocserv-agent"
    - name: RUNNER_LABELS
      value: "self-hosted,linux,x64,debian,docker,security-scan,deb-build"
    - name: BUILDAH_ISOLATION
      value: "chroot"
    - name: STORAGE_DRIVER
      value: "vfs"

    # Volume mounts
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: podman-socket
      mountPath: /var/run/docker.sock

    # Security context
    securityContext:
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        add:
        - NET_ADMIN
        drop:
        - ALL

    # Resources (optional but recommended)
    resources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"

  # Volumes
  volumes:
  - name: workspace
    hostPath:
      path: /opt/projects/repositories
      type: Directory
  - name: podman-socket
    hostPath:
      path: /run/podman/podman.sock
      type: Socket

---
# ConfigMap for shared runner configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-config
data:
  REPO_URL: "https://github.com/dantte-lp/ocserv-agent"
  RUNNER_GROUP: "Default"
  # RUNNER_TOKEN should be set via environment file or secret
